name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b2efd505ba15165b553dcebc7a444b8e8ac36775b8f6f4409709f9db3265f83"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
