name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f75f976bb7c8b872df5959e66e39f31bc1249df6758ab9f306c9b3ca9e5c8dbe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
