name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "787f202ce0edebe36724a54fc507b3ed343939d015961017a24173ed1e7a94e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
