name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "630b30980230f6b12b3395907fba0aeb5091c35f4e78f5ce57dfd47864fac46c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
