name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91bcd264e6893d719e2ae9396810e70bf91f42728a8b176627c1eb4f49eb0983"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
