name = "Bt Beta"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0da108e2a6b37b9383c175140c87295374b119708cdfe3769d50ae915bdc546"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
